services:
  mc:
    image: itzg/minecraft-server:java8
    environment:
      EULA: true
      TYPE: canyon
      VERSION: b1.7.3
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
volumes:
  mc-data:
